version: '2'
services:
  tero-ftpd:
    build: ./tero-ftpd
    command: start-ftpd 
    entrypoint: /entrypoint.sh
    tty: true
    stdin_open: true 
    ports:
      - "20781:2121"
      - "30000-30000:30099-30099"
    volumes:
      - ./tero-ftpd/entrypoint.sh:/entrypoint.sh
      - ..:/tero-ftpd
      - ../uploads:/uploads