version: '2'
services:
  tero-ftpd:
    container_name: tero_ftpd
    environment:
      - TERO_FTP_HOST=${TERO_FTP_HOST}
      - TERO_FTP_PORT=${TERO_FTP_PORT}
      - TERO_FTP_ROOTDIR=${TERO_FTP_ROOTDIR}
      - PASSIVE_PORTS_MIN=${TERO_FTP_PASSIVE_PORTS_MIN}
      - PASSIVE_PORTS_MAX=${TERO_FTP_PASSIVE_PORTS_MAX}
      - DJANGO_LOGS=${DJANGO_LOGS}
      - DJANGO_DEBUG=False
      - PRODUCTION=1
      - CREATE_VIRTUALENV=${CREATE_VIRTUALENV}
      - INSTALL_REQUIREMENTS=${INSTALL_REQUIREMENTS}
      - PGSQL_NAME=${PGSQL_NAME}
      - PGSQL_USER=${PGSQL_USER}
      - PGSQL_SECRET=${PGSQL_SECRET}
      - PGSQL_HOST=${PGSQL_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FTPD_MASQUERADE_ADDRESS=${FTPD_MASQUERADE_ADDRESS}
